language: ruby
cache: bundler
install:
  - bundle install --path=vendor
script: bundle exec jekyll build
rvm:
  - 2.5.1
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: _site/
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

after_success:
  - git remote add output https://${GH_TOKEN}github.com/chpmnrssll/static-output.git
  - git push output https://${GH_TOKEN}github.com/chpmnrssll/static-output.git
