language: ruby
cache: bundler
install:
  - bundle install --path=vendor
script: bundle exec jekyll build
rvm:
  - 2.5.1
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: _site/
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
   branches:
      only:
        - Build

after_success:
  - git clone https://${GITHUB_TOKEN}github.com/chpmnrssll/static-output.git
  - cd static-output
  # - git checkout master
  # - cd ..
  # - cp -f _site/*.* static-output/
  - cp -rf ../_site .
  # - cd static-output
  - git add .
  - git commit -m "Generate static HTML output"
  - git push https://${GITHUB_TOKEN}github.com/chpmnrssll/static-output.git
